image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test-jvm:
  stage: test
  script:
    - ./gradlew jvmTest --parallel

test-linux:
  stage: test
  tags:
    - linux
  script:
    - ./gradlew linuxTest --parallel

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
