image: registry.gitlab.com/serebit/logkat

stages:
  - build
  - test
  - deploy

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses
  artifacts:
    paths:
      - build/
      - .gradle/

build-linux:
  stage: build
  tags:
    - linux
  script:
    - ./gradlew linuxMainKlibrary
    - ./gradlew linuxTestKlibrary
  artifacts:
    paths:
      - build/
      - .gradle/

build-mingw:
  stage: build
  image: openjdk:windowsservercore
  tags:
    - windows
  script:
    - gradlew mingwMainKlibrary
    - gradlew mingwTestKlibrary
  artifacts:
    paths:
      - build/
      - .gradle/

test-jvm:
  stage: test
  script:
    - ./gradlew jvmTest
  dependencies:
    - build-jvm

test-linux:
  stage: test
  tags:
    - linux
  script:
    - ./gradlew linuxTest
  dependencies:
    - build-linux

test-mingw:
  stage: test
  tags:
    - windows
  script:
    - gradlew mingwTest
  dependencies:
    - build-mingw

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  dependencies:
    - build-jvm
    - build-linux
    - build-mingw
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy-metadata:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-jvm
    - build-linux
  variables:
    BINTRAY_PUBLICATION: "metadata"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-jvm:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-jvm
  variables:
    BINTRAY_PUBLICATION: "jvm"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-linux:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-linux
  tags:
    - linux
  variables:
    BINTRAY_PUBLICATION: "linux"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-mingw:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-mingw
  tags:
    - windows
  variables:
    BINTRAY_PUBLICATION: "mingw"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
