image: registry.gitlab.com/serebit/logkat:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_DEPTH: 10
  DOCKER_DRIVER: overlay2

.deploy-conditions: &deploy-conditions
  dependencies:
    - build
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

build:
  stage: build
  script: ./gradlew assemble # TODO change this to build once kotlin 1.3.60 comes out
  artifacts:
    untracked: true

deploy-release:
  stage: deploy
  script: ./gradlew publishAllPublicationsToPublicRepository
  when: manual
  <<: *deploy-conditions

deploy-snapshot:
  stage: deploy
  script: ./gradlew publishAllPublicationsToSnapshotRepository
  variables:
    SNAPSHOT_VERSION: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  <<: *deploy-conditions

pages:
  stage: deploy
  script: ./gradlew dokka
  artifacts:
    paths:
      - public
  when: manual
  <<: *deploy-conditions
