image: registry.gitlab.com/serebit/logkat

stages:
  - build
  - test
  - deploy

build-metadata:
  stage: build
  script: ./gradlew metadataMainClasses metadataJar

build-jvm:
  stage: build
  script: ./gradlew jvmMainClasses jvmTestClasses jvmJar
  artifacts:
    paths:
      - build/
      - .gradle/

build-linuxX64:
  stage: build
  tags:
    - linux
  script: ./gradlew linuxX64MainKlibrary linuxX64TestKlibrary linkTestDebugExecutableLinux
  artifacts:
    paths:
      - build/
      - .gradle/

build-mingwX64:
  stage: build
  tags:
    - windows
  script: gradlew mingwX64MainKlibrary mingwX64TestKlibrary linkTestDebugExecutableMingw
  artifacts:
    paths:
      - build/
      - .gradle/

test-jvm:
  stage: test
  script: ./gradlew jvmTest
  dependencies:
    - build-jvm

test-linuxX64:
  stage: test
  tags:
    - linux
  script: ./gradlew linuxX64Test
  dependencies:
    - build-linuxX64

test-mingwX64:
  stage: test
  tags:
    - windows
  script: ./gradlew mingwX64Test
  dependencies:
    - build-mingwX64

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  dependencies:
    - build-jvm
    - build-linuxX64
    - build-mingwX64
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy-metadata:
  stage: deploy
  script: ./gradlew publishMetadataPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-metadata
  variables:
    BINTRAY_PUBLICATION: "metadata"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-jvm:
  stage: deploy
  script: ./gradlew publishJvmPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-jvm
  variables:
    BINTRAY_PUBLICATION: "jvm"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-linuxX64:
  stage: deploy
  script: ./gradlew publishLinuxPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-linuxX64
  tags:
    - linux
  variables:
    BINTRAY_PUBLICATION: "linuxX64"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-mingwX64:
  stage: deploy
  script: ./gradlew publishMingwPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-mingwX64
  tags:
    - windows
  variables:
    BINTRAY_PUBLICATION: "mingwX64"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
