image: registry.gitlab.com/serebit/logkat:0.4.3

stages:
  - build
  - test
  - deploy

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses
  artifacts:
    paths:
      - build/
      - .gradle/

build-linux:
  stage: build
  image: registry.gitlab.com/serebit/logkat:linux-0.4.3
  tags:
    - linux
  script:
    - ./gradlew linuxMainKlibrary
    - ./gradlew linuxTestKlibrary
  artifacts:
    paths:
      - build/
      - .gradle/

build-mingw:
  stage: build
  image: openjdk:windowsservercore
  tags:
    - windows
  script:
    - gradlew mingwMainKlibrary
    - gradlew mingwTestKlibrary
  artifacts:
    paths:
      - build/
      - .gradle/

test-jvm:
  stage: test
  script:
    - ./gradlew jvmTest
  dependencies:
    - build-jvm

test-linux:
  stage: test
  image: registry.gitlab.com/serebit/logkat:linux-0.4.3
  tags:
    - linux
  script:
    - ./gradlew linuxTest
  dependencies:
    - build-linux

test-mingw:
  stage: test
  image: openjdk:windowsservercore
  tags:
    - windows
  script:
    - gradlew mingwTest
  dependencies:
    - build-mingw

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  dependencies:
    - build-jvm
    - build-linux
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-jvm
    - build-linux
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
