image: registry.gitlab.com/serebit/logkat

stages:
  - build
  - deploy

build-metadata:
  stage: build
  script: ./gradlew metadataMainClasses metadataJar

build-jvm:
  stage: build
  script: ./gradlew jvmMainClasses jvmTestClasses jvmJar jvmTest
  artifacts:
    paths:
      - build/
      - .gradle/

build-linuxX64:
  stage: build
  tags:
    - linux
  script: ./gradlew linuxX64MainKlibrary linuxX64TestKlibrary linkTestDebugExecutableLinuxX64 linuxX64Test
  artifacts:
    paths:
      - build/
      - .gradle/

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  dependencies:
    - build-jvm
    - build-linuxX64
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy-metadata:
  stage: deploy
  script: ./gradlew publishMetadataPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-metadata
  variables:
    BINTRAY_PUBLICATION: "metadata"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-jvm:
  stage: deploy
  script: ./gradlew publishJvmPublicationToMavenLocal bintrayUpload
  dependencies:
    - build-jvm
  variables:
    BINTRAY_PUBLICATION: "jvm"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY

deploy-linuxX64:
  stage: deploy
  script: ./gradlew publishLinuxX64PublicationToMavenLocal bintrayUpload
  dependencies:
    - build-linuxX64
  tags:
    - linux
  variables:
    BINTRAY_PUBLICATION: "linuxX64"
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
