image: registry.gitlab.com/serebit/logkat:latest

stages:
  - build
  - test
  - deploy

build-jvm:
  stage: build
  script:
    - ./gradlew jvmMainClasses
    - ./gradlew jvmTestClasses
  artifacts:
    paths:
      - build/
      - source/build/
      - .gradle/

build-linux:
  stage: build
  tags:
    - linux
  script:
    - ./gradlew linuxKlibrary
    - ./gradlew linuxTestKlibrary
  artifacts:
    paths:
      - build/
      - source/build/
      - .gradle/

test-jvm:
  stage: test
  script:
    - ./gradlew jvmTest
  dependencies:
    - build-jvm

test-linux:
  stage: test
  tags:
    - linux
  script:
    - ./gradlew linuxTest
  dependencies:
    - build-linux

pages:
  stage: deploy
  script:
    - ./gradlew dokka
  dependencies:
    - build-jvm
    - build-linux
  when: manual
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - ./gradlew bintrayUpload
  dependencies:
    - build-jvm
    - build-linux
  when: manual
  only:
    refs:
      - master
    variables:
      - $BINTRAY_KEY
